### ISSUE TITLE
Missing a little help

### ISSUE THREAD

**Issue by Aybee** [sdavidg/firebugsnippets#1]
Hello, was searching for a tool to permanent save the history of console command block. This firebugsnippets was the only similar addon I can find.

Please can you write a short description into the readme on how to create and save a new snippet? I'm not able to save a snippet even if I click on "Guardar".

**Comment by sdavidg** [comment]
1) This add-on requires the following add-ons to work properly:
https://addons.mozilla.org/en-US/firefox/addon/firebug/

2) Open firebug
3) Go to the console and select "multiline"
4) Click on "snippets"
![1](https://cloud.githubusercontent.com/assets/4955944/16381644/d115d13c-3c7d-11e6-8036-e08732af651f.png)
5) click on "New Snippet"
![2](https://cloud.githubusercontent.com/assets/4955944/16381706/20491da4-3c7e-11e6-97a0-c91c7e5ee70e.png)
6) Write your snippet and click on save

**Comment by Aybee** [comment]
That's what I tried and did not work as mentioned in ticket #3
