### ISSUE TITLE
Mixed languages

### ISSUE THREAD

**Issue by Aybee** [sdavidg/firebugsnippets#2]
Some text I see in English and some in Spain.

e.g.
- Default group
- New snippet 
- Admin groups
- Type any key to filter list
- grupo al que pertenece
- Guardar
- Cancelar

If this is fixed I will provide a german trnslation.

**Comment by sdavidg** [comment]
I will correct soon. 

>  I will provide a german trnslation.

Firebug will stop working soon. Read more: https://blog.getfirebug.com/2016/06/07/unifying-firebug-firefox-devtools/
I don't know if I'll write a new version for Firefox DevTools, but if you provide the translation I'll include in the new version

**Comment by Aybee** [comment]
To me this does not looks like Firebug stops working. On the contrary they try to make it better and comming close to the dev tools.

I will do the translation if you decide to work on the code and bring out a new fixed version.

Thank you for your effort.

**Comment by sdavidg** [comment]
I can't see this options:
- grupo al que pertenece
- Guardar
- Cancelar

> To me this does not looks like Firebug stops working

Firebug will disappear as addon. There are still some gaps to close: https://bugzilla.mozilla.org/show_bug.cgi?id=991806

**Comment by Aybee** [comment]
> I can't see this options:

I see this after clicking on "New snippet" in the pop up window.

> Firebug will disappear as addon.

So it remains to be seen whether there's a snippet feature in new version.

**Comment by Aybee** [comment]
Fixed with v 0.5. Thank you.
