### ISSUE TITLE
Can't save snippet nor select a group

### ISSUE THREAD

**Issue by Aybee** [sdavidg/firebugsnippets#3]
Unfortunately I can not save a snippet and the dropdown for selecting a group does not show any group.

**Comment by sdavidg** [comment]
This is a compatibility problem with the latest version of Firefox. I will correct soon.

Thanks for the report!

**Comment by Aybee** [comment]
Ok, thank you.

Meanwhile I've found https://addons.mozilla.org/en-US/firefox/addon/fire-snippets/?src=search which seems to work as well.

And https://addons.mozilla.org/en-US/firefox/addon/dafizilla-viewsourcewith/?src=search which simply offers an opportunity to save and load snippets from harddrive within firebug.

**Comment by sdavidg** [comment]
Try this: https://github.com/sdavidg/firebugsnippets/releases/tag/0.5

**Comment by Aybee** [comment]
This seems to work. Very good. Thank you.

Now I also see english text everywhere.

**Comment by Aybee** [comment]
Fixed with v 0.5. Thank you.
